@node data
@chapter data
@anchor{#data}

Filler Inserted By Treedoc.

@node 01folder
@chapter 01folder
@anchor{#folder}

Filler Inserted By Treedoc.

@node 01file
@chapter 01file
@anchor{#file}

@node One!
@chapter One!
@anchor{#one}

Test thing @emph{italic}

Another thing @emph{something}

A third thing @strong{bold}

@menu
* Two!::
@end menu

@node Two!
@section Two!
@anchor{#two}
Abbabaa

@menu
* Three!::
@end menu

@node Three!
@subsection Three!
@anchor{#three}
Aabbabab
@node 02file
@chapter 02file
@anchor{#file}
two!
@node 02folder
@chapter 02folder
@anchor{#folder}
Filler Inserted By Treedoc.
@node 03file
@chapter 03file
@anchor{#file}
Three!
@node 04file
@chapter 04file
@anchor{#file}
Four!
