* Concerns
** Sphinx works like so:

ReST files -> Many pretty outputs

If it starts with ReST, why not just use ReST as the default format for borg? Is
there any reason I need to create a new format when ReST already is in use?

*** Resolution:

Org Mode is More Powerful.

Also, here's another property of the current situation which might make the
decision more straight forward: Languages have their own preferred documentation
format. Java has JavaDoc, Perl has POD, Python has ReST/Sphinx, C++ has
Doxygen. All of these are nicely integrated with the language but with nothing
else, except maybe nice looking presentation formats. Having a language agnostic
tool should mean having a language agnostic format. Org also has babel to
include source in the documentation, which is cool.

** Doxygen works like so:

Comments in source -> A few pretty outputs

This makes sense to assimilate. Having documentation in the source is nice, but
when just using existing entities, looking up their documentation in the central
format is better.
