* Purpose

Pandoc: Converts a markup file or set of markup files well.

Treedoc: Reads markup files into an ordered tree (according to known formats),
converts them with pandoc, and writes them into another ordered tree format.

* Is This Useful?

Yes. Local documentation resources are more complete, editable, quickly
searchable (Example: ~C-h S~ in emacs), permanent, and not centralized!

* Capabilities

Treedoc currently knows of two formats.

1. Generic Markup

   Generic Markup is the term I use for trees of markup files and directory
   organized by the file system. Every inner node is a directory and every leaf
   is a markup file. The leaves are ordered according to the output from
   ~listDirectory~.

   Reading and writing generic markup trees is implemented.

2. Texinfo

   Texinfo files are single files made up of chapters, sections, and
   subsections. These are considered nodes of a tree by Treedoc.

   Writing Texinfo files is implemented.

More will come after the current code is cleaned up. Next focus will probably be
HTML.

* Usage

#+BEGIN_SRC shell
  treedoc [treedoc-options] [pandoc-options] input
#+END_SRC

Order of treedoc options and pandoc options is not restricted.
