\input texinfo
@documentencoding UTF-8

@ifnottex
@paragraphindent 0
@end ifnottex
@titlepage
@title Meet the Team
@end titlepage

@node Top
@top Meet the Team

@{% raw %@}

@verbatim
<h2 id="active-core-team-members">
  Active Core Team Members
  <button
    v-if="geolocationSupported && !userPosition"
    @click="getUserPosition"
    :disabled="isSorting"
    class="sort-by-distance-button"
  >
    <i
      v-if="isSorting"
      class="fa fa-refresh rotating-clockwise"
    ></i>
    <template v-else>
      <i class="fa fa-map-marker"></i>
      <span>find near me</span>
    </template>
  </button>
</h2>

<p v-if="errorGettingLocation" class="tip">
  Failed to get your location.
</p>

<p>
  The development of Vue and its ecosystem is guided by an international team, some of whom have chosen to be featured below.
</p>

<p v-if="userPosition" class="success">
  The core team has been sorted by their distance from you.
</p>

<vuer-profile
  v-for="profile in sortedTeam"
  :key="profile.name"
  :profile="profile"
  :title-visible="titleVisible"
></vuer-profile>
@end verbatim

@verbatim
<h2 id="core-team-emeriti">
  Core Team Emeriti
</h2>

<p>
  Here we honor some no-longer-active core team members who have made valuable contributions in the past.
</p>

<vuer-profile
  v-for="profile in teamEmeriti"
  :key="profile.name"
  :profile="profile"
  :title-visible="titleVisible"
></vuer-profile>
@end verbatim

@verbatim
<h2 id="community-partners">
  Community Partners
  <button
    v-if="geolocationSupported && !userPosition"
    @click="getUserPosition"
    :disabled="isSorting"
    class="sort-by-distance-button"
  >
    <i
      v-if="isSorting"
      class="fa fa-refresh rotating-clockwise"
    ></i>
    <template v-else>
      <i class="fa fa-map-marker"></i>
      <span>find near me</span>
    </template>
  </button>
</h2>

<p v-if="errorGettingLocation" class="tip">
  Failed to get your location.
</p>

<p>
  Some members of the Vue community have so enriched it, that they deserve special mention. We've developed a more intimate relationship with these key partners, often coordinating with them on upcoming features and news.
</p>

<p v-if="userPosition" class="success">
  The community partners have been sorted by their distance from you.
</p>

<vuer-profile
  v-for="profile in sortedPartners"
  :key="profile.name"
  :profile="profile"
  :title-visible="titleVisible"
></vuer-profile>
@end verbatim

@{% endraw %@}

@bye
